const path = require('path')
require('../../fs/example/fs.state')
let res = path.join('foo')
console.log(res)
res = path.join('foo','/bar')
console.log(res)
res = path.join('foo','/bar','..')
console.log(res)
res = path.join('foo','/bar','..','/')
console.log(res,__dirname)